

export const tagList = [
    {
        label:"户外",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"露营",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"绿道",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"爬山",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"野钓",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"滑雪",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"古迹",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"寺庙",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"游乐场",
        value:1,
        color:'#2db7f5'
    },{
        label:"公园",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"酒店",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"漂流",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"攀岩",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"跳伞",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"亲子",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"轮渡",
        value:1,
        color:'#2db7f5'
    },
    {
        label:"农场",
        value:1,
        color:'#2db7f5'
    },

    
]